FROM python:3.7-alpine3.15
WORKDIR /home/michal/Pulpit
ADD /home/michal/Pulpit/Jenkins/workspace/Git_weebhook/convert_data.py .
ADD /home/michal/Pulpit/Jenkins/workspace/Git_weebhook/data.txt .
ENTRYPOINT ["python", "convert_data.py", "data.txt"]
